# -*- mode: dockerfile -*-
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# Dockerfile to test MXNet on RaspberryPi emulation

FROM ubuntu:16.04

COPY install/ubuntu_arm_test.sh /work/
RUN /work/ubuntu_arm_test.sh

WORKDIR /work/deps

RUN wget -c -nv http://downloads.raspberrypi.org/raspbian/images/raspbian-2018-04-19/2018-04-18-raspbian-stretch.zip && \
    export R_ZIP=`find . -type f -iname "*-raspbian-*.zip"` && \
    unzip ${R_ZIP} && \
    rm -rf ${R_ZIP} && \
    export R_IMAGE=`find . -type f -iname "*-raspbian-*.img"`


# bootstrap

# launch

COPY runtime_test_functions.sh /work/
WORKDIR /work


# remove

# unmount

